# Run defined tests with pytest
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      ASSISTANT_NAME: ${{ secrets.ASSISTANT_NAME }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry self add setuptools
        poetry install
        poetry run pip install setuptools
    - name: pytest
      run: |
        poetry run pytest -p no:warnings --tb=line
